apiVersion: v1
kind: Service
metadata:
  name: kubeon
  namespace: kubeon
  labels:
    app.kubernetes.io/name: kubeon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubeon
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
